obj-y += vl53L1/
obj-y += power/
obj-y += aw8697_haptic/
#ifdef OPLUS_FEATURE_TP_BASIC
obj-y += oplus_touchscreen/
obj-y += touch.o
#endif
obj-y  += oplus_fp_drivers/
obj-y  += tri_state_key/
obj-y	+=  project_info/